spring.application.name=exam_point_server
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:mysql://localhost:3306/examdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.root=warn

#mail service config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=puneet.y@somaiya.edu
spring.mail.password=aovmzujpvmytilmf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

upload.dir=src/main/resources/static/images/profiles

#payment credentials
paypal.client-id=AU06lIPNQMm0onL8NczeNhNE3OhQgm4R31VSqnzbRIQIWYeZSAC1dwvAqTEfNzU_c68it7yVvkzSM99H
paypal.client-secret=ECdPA1hUYLd2ZqOGCgEDkqjskLNad2qM3499U1O0jtS0tWfUL92bghI03Zkd6ZMU-rOv9r9d1t4YQ9UN
paypal.mode=sandbox

